# Production
services:
  app_sidispem:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRETS=${JWT_SECRETS}
      - VERIFY_CREATE_USER=${VERIFY_CREATE_USER}
    ports:
      - "3002:3001"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - db_sidispem
    restart: always
    command: ["npm", "run", "start:prod"]
  db_sidispem:
    image: postgres:latest
    container_name: postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRETS=${JWT_SECRETS}
      - VERIFY_CREATE_USER=${VERIFY_CREATE_USER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TOKEN_IMPORT=${TOKEN_IMPORT}
      - ENDPOINT_URL=${ENDPOINT_URL}
      - R2_KEY=${R2_KEY}
      - R2_KEY_SECRETS=${R2_KEY_SECRETS}
      - BUCKET_NAME=${BUCKET_NAME}
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
    driver: local
